#@ load("@ytt:data", "data")
#@ load("common.lib.star", "resourceLabels")
#@ v = data.values

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: #@ v.name + "-tokens"
  labels: #@ resourceLabels(v)
data:
  GITHUB_TOKEN: #@ v.tokens.github
  GITLAB_TOKEN: #@ v.tokens.gitlab
