services:
  gimie_api:
    environment:
      env_file: .env
    build:
      context: ../..
      dockerfile: ./tools/image/Dockerfile
    container_name: "gimie-api"
    ports:
      - "7123:15400"
    volumes:
      - ../../src/:/app/src
