name: Deploy MS to Dev

on:
    workflow_dispatch:
#   push:
#     branches: [ main, feature-* ] # or just main, adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into remote and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /imaging-plaza/gimieapi
            # Use $GITHUB_REF_NAME to dynamically checkout the branch that triggered this action
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            
            docker stop gimieapi || true
            docker rm gimieapi || true
            docker build -t gimieapi .
            docker run -d --name gimieapi -p 7000:15400 gimieapi